# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dialoghelper',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/dialoghelper',
                'lib_path': 'dialoghelper'},
  'syms': {'dialoghelper.core': {'dialoghelper.core.get_db': ('core.html#get_db', 'dialoghelper/core.py')}}}
