"""Experimental `dialoghelper` capabilities."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_capture.ipynb.

# %% auto 0
__all__ = ['iife', 'start_share', 'capture_screen']

# %% ../nbs/01_capture.ipynb
from .core import *
from fastcore.all import *
from fasthtml.common import Div,Script
from httpx import post as xpost
from importlib import resources
from lisette.core import *

import base64,json,time,uuid

# %% ../nbs/01_capture.ipynb
def iife(code: str) -> str:
    "Wrap javascript code string in an IIFE and execute it via `add_html`"
    trigger_script = f'''
(async () => {{
{code}
}})();
'''
    add_html(Div(Script(trigger_script), hx_swap_oob=f'beforeend:#js-script'))

# %% ../nbs/01_capture.ipynb
def start_share():
    iife((resources.files('dialoghelper')/'screenshot.js').read_text())
    iife('await setupVideoStream();')

# %% ../nbs/01_capture.ipynb
def capture_screen(timeout:int=15):
    'Capture screenshot. Always re-call this when a fresh view may be needed.'
    idx = uuid.uuid4()
    iife(f"pushData('{idx}', {{img_data: await getScreenshot()}});")
    url = 'http://localhost:5001/pop_data_blocking_'
    d = dict2obj(xpost(url, data={'data_id': idx, 'timeout': timeout}).json())
    if 'img_data' in d: return ToolResponse([{'type': 'image_url', 'image_url': d.img_data}])
    else: return f'Capture failed: {d.error}'
