# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['get_db']

# %% ../nbs/00_core.ipynb 2
import inspect, json, importlib, linecache
from tempfile import TemporaryDirectory
from fasthtml.common import *
from httpx import get as xget
from fastcore.utils import *
from ghapi.all import *
from fastlite import *

# %% ../nbs/00_core.ipynb 3
def get_db():
    if os.environ.get('IN_SOLVEIT', False): dataparent,nm = Path('/app'),'data.db'
    else: dataparent,nm = Path('..'),'dev_data.db'
    db = database(dataparent/'data'/nm)
    all_dcs(db)
    return db
