"""Docs: https://AnswerDotAI.github.io/dialoghelpercore.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['dh_settings', 'Placements', 'mermaid_url', 'msg_insert_line', 'msg_str_replace', 'msg_strs_replace',
           'msg_replace_lines', 'msg_del_lines', 'msg_python', 'names_containing', 'find_dname', 'xposta', 'xgeta',
           'call_endp', 'call_endpa', 'curr_dialog', 'msg_idx', 'add_html_a', 'add_html', 'add_scr_a', 'add_scr',
           'iife_a', 'iife', 'add_mod', 'add_mod_a', 'pop_data_a', 'pop_data', 'fire_event_a', 'fire_event',
           'event_get_a', 'event_get', 'trigger_now', 'event_once', 'event_once_a', 'js_run', 'js_run_a', 'js_eval',
           'js_eval_a', 'display_response', 'connfiles', 'realpath', 'list_dialogs', 'read_msg', 'find_msgs',
           'view_dlg', 'add_msg', 'read_msgid', 'view_msg', 'msg_ref', 'del_msg', 'run_and_prompt', 'update_msg',
           'run_msg', 'copy_msg', 'paste_msg', 'enable_mermaid', 'mermaid', 'toggle_header', 'toggle_bookmark',
           'toggle_comment', 'url2note', 'create_or_run_dialog', 'stop_dialog', 'load_dialog', 'rm_dialog',
           'run_code_interactive', 'solveit_docs', 'dialog_link', 'spawn_agent', 'search', 'searches', 'web_answer']

# %% ../nbs/00_core.ipynb #4dd4b925
import os,re,inspect,ast,collections,time,asyncio,json,linecache,importlib,difflib,uuid,builtins,subprocess

from typing import Dict
from tempfile import TemporaryDirectory
from ipykernel_helper import *
from dataclasses import dataclass
from os.path import normpath
from fastcore.xml import to_xml
from fastcore.meta import splice_sig, delegates, delegated

from fastcore.utils import *
from fastcore.xtras import asdict,acache
from fastcore.docments import MarkdownRenderer
from ghapi.all import *
from inspect import currentframe,Parameter,signature
from httpx import AsyncClient, get as xget, post as xpost
from IPython.display import display,Markdown,HTML
from monsterui.all import franken_class_map,apply_classes
from toolslm.xml import *
from fasthtml.common import *
from fasthtml.components import Solveit_input
from urllib.parse import urlencode
from safepyrun import RunPython,find_var,create_python_magic,load_ipython_extension
from functools import cache
from pyskills import allow
from pyskills.edit import *

# %% ../nbs/00_core.ipynb #c9936691
_lt = import_no_init('lisette.types')

# %% ../nbs/00_core.ipynb #eb1636a6
dh_settings = {'port':5001}
# dh_settings = {'port':6001}

# %% ../nbs/00_core.ipynb #f5cd76ed
try: load_ipython_extension(get_ipython())
except NameError: pass

# %% ../nbs/00_core.ipynb #9ec900cf
def names_containing(s:str):
    "Names containing `s` in IPython user namespace, or caller globals"
    try: ip = get_ipython()
    except NameError: ip = None
    ns = getattr(ip, 'user_ns', None) or currentframe().f_back.f_globals
    return [o for o in ns if s in o]

# %% ../nbs/00_core.ipynb #65a8b58b
def find_dname(dname=None, required=True):
    "Get the dialog name by searching the call stack for __dialog_name, and resolving `dname` if supplied."
    if dname:
        dname = dname.removesuffix('.ipynb')
        if dname.startswith('/'): return dname
    curr = dh_settings.get('dname', None)
    if not curr: curr = os.getenv('__DIALOG_NAME')
    if not curr:
        if required: curr = find_var('__dialog_name')
        else: return None
    if not curr: raise ValueError("No dialog context: Please pass absolute `dname` starting with '/'")
    if not dname: return '/'+curr
    p = Path(curr).parent
    res = normpath((p/dname))
    assert '../' not in res, "Path traversal not permitted"
    return '/'+res

# %% ../nbs/00_core.ipynb #a01ad161
def _diff_dialog(pred, dname, err="`id` parameter must be provided when target dialog is different", id=None):
    "Raise ValueError if targeting a different dialog, `pred` is True, and no `id` provided"
    if not pred or id: return
    if dname or ('dname' in dh_settings): raise ValueError(err)

# %% ../nbs/00_core.ipynb #39232620
@allow
async def xposta(url, **kwargs):
    async with AsyncClient() as c: return await c.post(url, **kwargs)
@allow
async def xgeta(url, **kwargs):
    async with AsyncClient() as c: return await c.get (url, **kwargs)

# %% ../nbs/00_core.ipynb #bdac4ecb
def _prep_endp(path, dname, json, id, data, required=True):
    dname = find_dname(dname, required=required)
    if dname: data['dlg_name'] = dname.strip('/')
    if id: data['id_'] = id
    data = {k:v for k,v in data.items() if v is not None}
    url = f'http://localhost:{dh_settings["port"]}/{path}'
    headers = {'Accept': 'application/json'} if json else {}
    return url, data, headers

def _handle_resp(res, json, raiseex):
    if raiseex: res.raise_for_status()
    try: return adict(res.json()) if json else res.text
    except Exception: return res.text

# %% ../nbs/00_core.ipynb #5fc896fe
def call_endp(path, dname='', json=False, raiseex=False, id=None, required=True, timeout=10, **data):
    url, data, headers = _prep_endp(path, dname, json, id, data, required=required)
    return _handle_resp(xpost(url, data=data, headers=headers, timeout=timeout), json, raiseex)

async def call_endpa(path, dname='', json=False, raiseex=False, id=None, required=True, timeout=10, **data):
    url, data, headers = _prep_endp(path, dname, json, id, data, required=required)
    return _handle_resp(await xposta(url, data=data, headers=headers, timeout=timeout), json, raiseex)

# %% ../nbs/00_core.ipynb #1a5b4b75
def _check_res(res, dname):
    "Check if a route call succeeded; return success or error dict"
    if not res: return {'error': f'Dialog {dname} may not be running, or message not found'}
    return {'success': 'complete'}

# %% ../nbs/00_core.ipynb #a9cb5512
async def curr_dialog(
    with_messages:bool=False,  # Include messages as well?
    dname:str='' # Dialog to get info for; defaults to current dialog
) -> dict|str:
    "Get the current dialog info."
    res = await call_endpa('curr_dialog_', dname, json=True, with_messages=with_messages)
    if 'error' in res: return f"error: {res['error']}"
    if res: return {'name': res['name'], 'mode': res['mode']}

# %% ../nbs/00_core.ipynb #8810450f
async def msg_idx(
    id:str=None,  # Message id to find (defaults to current message)
    dname:str='' # Dialog to get message index from; defaults to current dialog
) -> int:
    "Get absolute index of message in dialog."
    _diff_dialog(True, dname, id=id)
    res = await call_endpa('msg_idx_', dname, json=True, id=id)
    return (await call_endpa('msg_idx_', dname, json=True, id=id))['idx']

# %% ../nbs/00_core.ipynb #c43c4361
async def add_html_a(
    content:str, # The HTML to send to the client (generally should include hx-swap-oob)
    dname:str='' # Dialog to get info for; defaults to current dialog
):
    "Send HTML to the browser to be swapped into the DOM"
    await call_endpa('add_html_', dname, content=to_xml(content))
    return {'success': 'Content added to DOM'}

def add_html(
    content:str, # The HTML to send to the client (generally should include hx-swap-oob)
    dname:str='' # Dialog to get info for; defaults to current dialog
):
    "Send HTML to the browser to be swapped into the DOM"
    call_endp('add_html_', dname, content=to_xml(content))
    return {'success': 'Content added to DOM'}

# %% ../nbs/00_core.ipynb #4b43e4e9
async def add_scr_a(scr, oob='innerHTML:#ephemeral'):
    "Swap a script element to the end of the ephemeral element"
    if isinstance(scr,str): scr = Script(scr)
    await add_html_a(Div(scr, hx_swap_oob=oob))

def add_scr(scr, oob='innerHTML:#ephemeral'):
    "Swap a script element to the end of the ephemeral element"
    if isinstance(scr,str): scr = Script(scr)
    add_html(Div(scr, hx_swap_oob=oob))

# %% ../nbs/00_core.ipynb #6f1b12d3
def _iife_scr(code: str):
    return f'''
(async () => {{
{code}
}})();
'''

async def iife_a(code: str):
    "Wrap javascript code string in an IIFE and execute it via `add_html`"
    await add_scr_a(_iife_scr(code))

def iife(code: str):
    "Wrap javascript code string in an IIFE and execute it via `add_html`"
    add_scr(_iife_scr(code))

def add_mod(s:str):
    "Wrap javascript code string in a js script module and add it via `add_html`"
    add_scr(Script(s, type="module"))

async def add_mod_a(s:str):
    "Wrap javascript code string in a js script module and add it via `add_html`"
    await add_scr_a(Script(s, type="module"))

# %% ../nbs/00_core.ipynb #99a07c05
async def pop_data_a(idx, timeout=15):
    return dict2obj(await call_endpa('pop_data_blocking_', data_id=idx, timeout=timeout, json=True))

def pop_data(idx, timeout=15):
    return dict2obj(call_endp('pop_data_blocking_', data_id=idx, timeout=timeout, json=True))

# %% ../nbs/00_core.ipynb #ddcee8d5
def _fire_event_scr(evt, data=None):
    params = f"'{evt}'"
    if data is not None: params += f", {json.dumps(data)}"
    return Script(f"htmx.trigger(document.body, {params});", id='js-event', hx_swap_oob='true')

async def fire_event_a(evt:str, **data): await add_html_a(_fire_event_scr(evt, data))
def fire_event(evt:str, **data): add_html(_fire_event_scr(evt, data))

# %% ../nbs/00_core.ipynb #25ed8a64
def _event_prep(data):
    idx = uuid.uuid4()
    return idx, (data or {}) | {'idx': str(idx)}

async def event_get_a(evt:str, timeout=15, **data):
    "Call `fire_event` and then `pop_data` to get a response"
    idx, data = _event_prep(data)
    await fire_event_a(evt, **data)
    return await pop_data_a(idx, timeout)

def event_get(evt:str, timeout=15, **data):
    "Call `fire_event` and then `pop_data` to get a response"
    idx, data = _event_prep(data)
    fire_event(evt, **data)
    return pop_data(idx, timeout)

# %% ../nbs/00_core.ipynb #e2d1a5be
def trigger_now(evt, data=None, ttl=5000):
    "Synchronously trigger a browser event, safe against replay"
    ts = time.time_ns() // 1_000_000
    params = f"'{evt}'"
    guard = f'window["_trig_{ts}"]'
    if data is not None: params += f", {json.dumps(data)}"
    display(HTML(f'''<script>
if (Date.now() - {ts} < {ttl} && !{guard}) {{
    {guard}=1;
    htmx.trigger(document.body, {params});
}}</script>'''))

# %% ../nbs/00_core.ipynb #0069cc4f
def event_once(evt, timeout=15, ttl=5000, **data):
    "Like event_get but with replay/dedup safety via trigger_now"
    idx, data = _event_prep(data)
    trigger_now(evt, data, ttl=ttl)
    return pop_data(idx, timeout)

async def event_once_a(evt, timeout=15, ttl=5000, **data):
    "Like event_get_a but with replay/dedup safety via trigger_now"
    idx, data = _event_prep(data)
    trigger_now(evt, data, ttl=ttl)
    await asyncio.sleep(0)
    return await pop_data_a(idx, timeout)

# %% ../nbs/00_core.ipynb #4f4a6d69
def js_run(code):
    "Run JS code that calls done() when finished, and wait for result"
    idx, data = _event_prep({})
    iife("const done = (data={}) => pushData('%s', {ready: true, ...data}); %s" % (idx, code))
    return pop_data(idx)

async def js_run_a(code):
    "Run JS code that calls done() when finished, and wait for result"
    idx, data = _event_prep({})
    await iife_a("const done = (data={}) => pushData('%s', {ready: true, ...data}); %s" % (idx, code))
    return await pop_data_a(idx)

# %% ../nbs/00_core.ipynb #3f1c1de7
def js_eval(expr):
    "Evaluate a JS expression in the browser and return the result"
    idx, data = _event_prep({})
    iife("pushData('%s', (() => { %s })())" % (idx, expr))
    return pop_data(idx)

async def js_eval_a(expr):
    "Evaluate a JS expression in the browser and return the result"
    idx, data = _event_prep({})
    await iife_a("pushData('%s', (() => { %s })())" % (idx, expr))
    return await pop_data_a(idx)

# %% ../nbs/00_core.ipynb #80334098
def display_response(display:str, result:str=None):
    "Return a special response where `display` is added as markdown/HTML to the prompt output, and `result` is returned to the LLM"
    if result is None: result = f"The following has been added to the user's markdown/HTML dialog response:\n{display}"
    return _lt.ToolResponse({'_display': display, 'result': result})

# %% ../nbs/00_core.ipynb #1f0c6004
from fastcore.script import call_parse

# %% ../nbs/00_core.ipynb #677693ee
@call_parse
async def connfiles(
    dlg_name:str='' # Name of dialog to get connfile path for; if empty, return dict of all running dialogs with their paths
):
    "Get a running dialogs' connection file path (or dict of all of them if no `dlg_name`."
    res = await call_endpa('connfiles_', json=True, required=False)
    if dlg_name: return res[dlg_name.removeprefix('/').removesuffix('.ipynb')]
    return res

# %% ../nbs/00_core.ipynb #e2138315
@acache
async def realpath(
    subpath:str='/' # Path under data root (absolute with `/`, else relative to current dialog's folder)
) -> str:
    "Get the real on-disk path to solveit `subpath`. '/' gets on-disk base path."
    sub = find_dname(subpath) if subpath else str(Path(find_dname()).parent)
    return await call_endpa('realpath_', subpath=sub.lstrip('/'))

# %% ../nbs/00_core.ipynb #dab9c929
async def list_dialogs(
    subpath:str='', # Path under data root (absolute with `/`, else relative to current dialog's folder)
    depth:int=1 # Directory depth
) -> dict:
    "List dialogs and folders under `subpath`. Folders have `/` suffix."
    d = find_dname(subpath, required=False)
    sub = (d or '') if subpath else (str(Path(d).parent) if d else '')
    return await call_endpa('list_dialogs_', json=True, required=False, subpath=sub.lstrip('/'), depth=depth)

# %% ../nbs/00_core.ipynb #f819e9bd
def _maybe_xml(res, as_xml, key=None):
    if as_xml: return res
    res = loads(res)
    if 'error' in res: return res
    if key: res = res[key]
    return dict2obj(res)

# %% ../nbs/00_core.ipynb #558c6aa7
async def read_msg(
    n:int=-1,      # Message index (if relative, +ve is downwards)
    relative:bool=True,  # Is `n` relative to current message (True) or absolute (False)?
    id:str=None,  # Message id to find (defaults to current message)
    view_range:list[int,int]=None, # Optional 1-indexed (start, end) line range for files, end=-1 for EOF
    nums:bool=False, # Whether to show line numbers
    dname:str='' # Dialog to get info for; defaults to current dialog
    ) -> dict:
    """Get the message indexed in the current dialog.
    NB: Messages in the current dialog above the current message are *already* visible; use this only when you need line numbers for editing operations, or for messages not in the current dialog or below the current message.
    - To get the exact message use `n=0` and `relative=True` together with `id`.
    - To get a relative message use `n` (relative position index).
    - To get the nth message use `n` with `relative=False`, e.g `n=0` first message, `n=-1` last message.
    {dname}"""
    _diff_dialog(relative, dname, "`id` parameter must be provided, or use `relative=False` with `n`, when target dialog is different", id=id)
    data = dict(n=n, relative=relative, id=id)
    if view_range: data['view_range'] = view_range # None gets converted to '' so we avoid passing it to use the p.default
    if nums: data['nums'] = nums
    return await call_endpa('read_msg_', dname, json=True, **data)

# %% ../nbs/00_core.ipynb #6a4aa03b
async def find_msgs(
    re_pattern:str='', # Optional regex to search for (re.DOTALL+re.MULTILINE is used)
    msg_type:str=None, # optional limit by message type ('code', 'note', or 'prompt')
    before:int=0,  # Include additional n msgs before matches
    after:int=0,   # Include additional n msgs before matches
    context:int=0, # Include additional n msgs around matches (recommended: set `context=2` when searching to see ipynb context)
    use_case:bool=False, # Use case-sensitive matching?
    use_regex:bool=True, # Use regex matching?
    only_err:bool=False, # Only return messages that have errors?
    only_exp:bool=False, # Only return messages that are exported?
    only_chg:bool=False, # Only return messages that have changed vs git HEAD?
    ids:str='', # Optionally filter by comma-separated list of message ids
    limit:int=None, # Optionally limit number of returned items
    include_output:bool=True, # Include output in returned dict?
    include_meta:bool=True, # Include all additional message metadata
    as_xml:bool=False, # Use concise unescaped XML output format
    nums:bool=False, # Show line numbers?
    trunc_out:bool=False, # Middle-out truncate code output to 100 characters?
    trunc_in:bool=False, # Middle-out truncate cell content to 80 characters?
    headers_only:bool=False, # Only return note messages that are headers (first line only); cannot be used together with `header_section`
    header_section:str=None, # Find section starting with this header; returns it plus all children
    include_skipped:bool=False, # Include messages hidden from AI (skipped)?
    dname:str='' # Dialog to get info for; defaults to current dialog
)->list[dict]: # Messages in requested dialog that contain the given information
    """Often it is more efficient to call `view_dlg` (not `find_msgs`) to see the whole dialog, so you can use it all from then on.
    {dname}
    Message ids are identical to those in LLM chat history, so do NOT call this to view a specific message if it's in the chat history--instead use `view_msg`.
    Do NOT use find_msgs to view message content in the current dialog above the current prompt -- these are *already* provided in LLM context, so just read the content there directly. (NB: LLM context only includes messages *above* the current prompt, whereas `find_msgs` can access *all* messages.)
    To refer to a found message from code, use its `id` field."""
    res = await call_endpa('find_msgs_', dname, json=False, re_pattern=re_pattern, msg_type=msg_type, limit=limit, ids=ids,
                    use_case=use_case, use_regex=use_regex, only_err=only_err, only_exp=only_exp, only_chg=only_chg,
                    include_output=include_output, include_meta=include_meta, as_xml=as_xml, nums=nums,
                    trunc_out=trunc_out, trunc_in=trunc_in, before=before, after=after, context=context,
                    headers_only=headers_only, header_section=header_section, include_skipped=include_skipped)
    return _maybe_xml(res, as_xml=as_xml, key='msgs')

# %% ../nbs/00_core.ipynb #9ff2a38e
async def view_dlg(
    dname:str='', # Dialog to get info for; defaults to current dialog
    msg_type:str=None, # optional limit by message type ('code', 'note', or 'prompt')
    nums:bool=False, # Whether to show line numbers
    include_output:bool=False, # Include output in returned dict?
    trunc_out:bool=True, # Middle-out truncate code output to 100 characters (only applies if `include_output`)?
    trunc_in:bool=False, # Middle-out truncate cell content to 80 characters?
    include_skipped:bool=False, # Include messages hidden from AI (skipped)?
) -> str:
    "Concise XML view of all messages (optionally filtered by type), not including metadata. Often it is more efficient to call this to see the whole dialog at once (including line numbers if needed), instead of running `find_msgs` or `view_msg` multiple times."
    return await find_msgs(msg_type=msg_type, dname=dname, as_xml=True, nums=nums,
        include_meta=False, include_output=include_output, trunc_out=trunc_out, trunc_in=trunc_in, include_skipped=include_skipped)

# %% ../nbs/00_core.ipynb #fdc5a465
Placements = str_enum('Placements', 'add_after', 'add_before', 'at_start', 'at_end')

# %% ../nbs/00_core.ipynb #5093cfe4
def _add_msg(
    output:str='', # Prompt/code output; Code outputs must be .ipynb-compatible JSON array
    time_run: str | None = '', # When was message executed
    is_exported: int | None = 0, # Export message to a module?
    skipped: int | None = 0, # Hide message from prompt?
    i_collapsed: int | None = 0, # Collapse input?
    o_collapsed: int | None = 0, # Collapse output?
    heading_collapsed: int | None = 0, # Collapse heading section?
    pinned: int | None = 0, # Pin to context?
): ...

# %% ../nbs/00_core.ipynb #ca694d38
@delegated(_add_msg)
async def _add_msg_unsafe(
    content:str, # Content of the message (i.e the message prompt, code, or note text)
    placement:str='', # Location to place message. Can be 'at_start' or 'at_end', and if id provided or in curr dlg can also be 'add_after' or 'add_before'. Defaults to 'at_end' if no id and not targeting curr dlg
    id:str=None, # id of message that placement is relative to (if None, uses current message)
    dname:str='', # Dialog to add to; defaults to current dialog (`run` only has a effect if dialog is currently running)
    msg_type: str='note', # Message type, can be 'code', 'note', or 'prompt'
    run:bool=False, # Run the message?
    wait:bool=False, # Wait for and return response? (if `run`)
    poll:float=0.5, # Frequency of polling to check for completion (if `wait`)
    **kwargs
)->str: # Message ID of newly created message
    """Add/update a message to the queue to show after code execution completes, and optionally run it.
    **NB**: when creating multiple messages in a row, after the 1st message set `id` to the result of the last `add_msg` call,
    otherwise messages will appear in the dialog in REVERSE order.
    *WARNING*--This can execute arbitrary code, so check carefully what you run!--*WARNING"""
    if not placement: placement = 'add_after' if id or not dname else 'at_end'
    _diff_dialog(placement not in ('at_start','at_end'), dname,
        "`id` or `placement='at_end'`/`placement='at_start'` must be provided when target dialog is different", id=id)    
    assert not (wait and not dname), "Can not wait in current dialog"
    res = await call_endpa('add_relative_', dname, json=True, content=content, placement=placement, id=id, msg_type=msg_type,
        run=run, **kwargs)
    if 'error' in res: return f"error: {res['error']}"
    rmsg_id = res['id']
    if not wait or not run: return rmsg_id
    while True:
        res = await read_msgid(rmsg_id, dname=dname)
        if not res.get('run', False): return res['output']
        await asyncio.sleep(poll)

# %% ../nbs/00_core.ipynb #3ad14786
@delegates(_add_msg_unsafe)
async def add_msg(
    content:str, # Content of the message (i.e the message prompt, code, or note text)
    msg_type: str='note', # Message type, can be 'code', 'note', or 'prompt'
    run:bool=False, # Run the message?
    **kwargs
)->str: # Message ID of newly created message
    """Add/update a message to the queue to show after code execution completes, and optionally run it.
    Code messages are run using python's restricted sandbox.
    **NB**: when creating multiple messages in a row, after the 1st message set `id` to the result of the last `add_msg` call,
    otherwise messages will appear in the dialog in REVERSE order.
    {dname}"""
    if msg_type=='code' and run: content = "%%py\n"+content
    return await _add_msg_unsafe(content=content, msg_type=msg_type, run=run, **kwargs)

# %% ../nbs/00_core.ipynb #afc62c45
async def read_msgid(
    id:str,  # Message id to find
    view_range:list[int,int]=None, # Optional 1-indexed (start, end) line range for files, end=-1 for EOF
    nums:bool=False, # Whether to show line numbers
    dname:str='', # Dialog to get message from; defaults to current dialog
    add_to_dlg:bool=False # Whether to add message content to current dialog (as a raw message)
) -> dict:
    """Get message `id`. Message IDs can be view directly in LLM chat history/context, or found in `find_msgs` results.
    Use `add_to_dlg` if the LLM or human may need to refer to the message content again later."""
    res = await read_msg(0, id=id, view_range=view_range, nums=nums, dname=dname)
    if add_to_dlg: await add_msg(res['content'], msg_type='raw')
    return res

# %% ../nbs/00_core.ipynb #801783c2
async def view_msg(
    id:str,  # Message id to view
    dname:str='', # Dialog to get message from; defaults to current dialog
    nums:bool=True, # Whether to show line numbers
    view_range:list[int,int]=None, # Optional 1-indexed (start, end) line range for files, end=-1 for EOF. Rarely needed--read whole message in nearly all cases instead
    add_to_dlg:bool=False # Whether to add message content to current dialog (as a raw message)
) -> str:
    """Views the *content* of message `id`. Same as `read_msgid(...)['content']`, defaulting to `nums=True`.
    Use `add_to_dlg` if the LLM or human may need to refer to the message content again later."""
    res = (await read_msg(0, id=id, view_range=view_range, nums=nums, dname=dname))['content']
    if add_to_dlg: await add_msg(res, msg_type='raw')
    return res

# %% ../nbs/00_core.ipynb #79cdeb39
def msg_ref(id, dname=None):
    "Markdown ref to a message — same-dialog `#id` or cross-dialog `#dname/id`"
    if not dname: return f'#{id}'
    return f'#{find_dname(dname).strip("/")}/{id}'

# %% ../nbs/00_core.ipynb #f1ee1903
async def del_msg(
    id:str=None, # id of message to delete
    dname:str='', # Dialog to get info for; defaults to current dialog
    log_changed:bool=False # Add a note showing the deleted content?
) -> dict:
    "Delete a message from the dialog. DO NOT USE THIS unless you have been explicitly instructed to delete messages."
    if log_changed: msg = await read_msgid(id, dname=dname)
    res = await call_endpa('rm_msg_', dname, raiseex=True, msid=id, json=True)
    if log_changed: await add_msg(f"> Deleted {msg_ref(id, dname)}\n\n```\n{msg.content}\n```")
    return res

# %% ../nbs/00_core.ipynb #30e90bf9
async def run_and_prompt(
    code: str,  # Python code to run
    prompt: str = "Continue.",  # Prompt to add after code execution
) -> str:
    "Run `code` and then run `prompt`, returning the resulting message ID."
    id = await add_msg(code, msg_type="code", run=True)
    await add_msg(prompt, msg_type="prompt", run=True, id=id)
    return _lt.StopResponse('Code has been added and queued for execution. Tool loop is finishing now. Summarize progress so far and planned next steps, and await "Continue." prompt.')

# %% ../nbs/00_core.ipynb #023dcb74
def _umsg(
    content:str|None=None, # Content of the message (i.e the message prompt, code, or note text)
    msg_type: str|None = None, # Message type, can be 'code', 'note', or 'prompt'
    output:str|None = None, # Prompt/code output; Code outputs must be .ipynb-compatible JSON array
    time_run: str | None = None, # When was message executed
    is_exported: int | None = None, # Export message to a module?
    skipped: int | None = None, # Hide message from prompt?
    i_collapsed: int | None = None, # Collapse input?
    o_collapsed: int | None = None, # Collapse output?
    heading_collapsed: int | None = None, # Collapse heading section?
    pinned: int | None = None # Pin to context?
): ...

# %% ../nbs/00_core.ipynb #38875a12
@delegates(_umsg)
async def update_msg(
    id:str=None, # id of message to update (if None, uses current message)
    msg:Optional[Dict]=None, # Dictionary of field keys/values to update
    dname:str='', # Dialog to get info for; defaults to current dialog
    log_changed:bool=False, # Add a note showing the diff?
    **kwargs) -> str:
    """Update an existing message. Provide either `msg` OR field key/values to update.
    - Use `content` param to update contents.
    - Only include parameters to update--missing ones will be left unchanged.
    {dname}"""
    if msg: kwargs |= msg.get('msg', msg)
    if not id: id = kwargs.pop('id', None)
    if not id: raise TypeError("update_msg needs either a dict message with and id, or `id=`")
    res = await call_endpa('update_msg_', dname, json=True, id=id, log_changed=log_changed, **kwargs)
    if 'error' in res: return f"error: {res['error']}"
    if log_changed:
        diff = res.get('diff', '')
        await add_msg(f'> Updated {msg_ref(id, dname)}\n\n' + (f'```diff\n{diff}\n```' if diff else 'No changes.'))
    return res['id']

# %% ../nbs/00_core.ipynb #316bd7a0
async def run_msg(
    ids:str=None, # Comma-separated ids of message(s) to execute
    dname:str='' # Running dialog to get info for; defaults to current dialog. (Note dialog *must* be running for this function)
):
    "Adds a message to the run queue. Use read_msg to see the output once it runs."
    return await call_endpa('add_runq_', dname, ids=ids, json=True)

# %% ../nbs/00_core.ipynb #73025e57
async def copy_msg(
    ids:str=None, # Comma-separated ids of message(s) to copy
    cut:bool=False, # Cut message(s)? (If not, copies)
    dname:str='' # Running dialog to copy messages from; defaults to current dialog. (Note dialog *must* be running for this function)
) -> dict:
    "Add `ids` to clipboard."
    id,*_ = ids.split(',')
    res = await call_endpa('msg_clipboard_', dname, ids=ids, id=id, cmd='cut' if cut else 'copy')
    return _check_res(res, dname)

# %% ../nbs/00_core.ipynb #80def27e
async def paste_msg(
    id:str=None, # Message id to paste next to
    after:bool=True, # Paste after id? (If not, pastes before)
    dname:str='' # Running dialog to copy messages from; defaults to current dialog. (Note dialog *must* be running for this function)
) -> dict:
    "Paste clipboard msg(s) after/before the current selected msg (id)."
    res = await call_endpa('msg_paste_', dname, id=id, after=after, json=True)
    return _check_res(res, dname)

# %% ../nbs/00_core.ipynb #13e9163a
mermaid_url = "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs"

def enable_mermaid():
    return Script("""
if (window.mermaid) mermaid.run()
else {
    import('%s').then(m => {
        window.mermaid = m.default;
        window.mermaid.run();
        htmx.onLoad(elt => {
            if (elt.matches('div.mermaid, pre.mermaid') || htmx.findAll(elt, 'div.mermaid, pre.mermaid')) window.mermaid.run();
        });
    });
}""" % mermaid_url, type="module")

# %% ../nbs/00_core.ipynb #f3d1e424
def mermaid(code, cls="mermaid", **kwargs):
    "A mermaid diagram"
    return Div(code, cls=cls, **kwargs)

# %% ../nbs/00_core.ipynb #b220e29b
async def toggle_header(
    id:str, # id of markdown header note message to toggle collapsed state
    dname:str='' # Running dialog to copy messages from; defaults to current dialog. (Note dialog *must* be running for this function)
) -> dict:
    "Toggle collapsed header state for `id`"
    res = await call_endpa('toggle_header_collapse_', dname, id=id)
    return _check_res(res, dname)

# %% ../nbs/00_core.ipynb #90b55ef4
async def toggle_bookmark(
    id:str, # id of message to toggle bookmark on
    n:int, # Bookmark number (1-9)
    dname:str='' # Dialog to set bookmark in; defaults to current dialog
) -> dict:
    "Toggle numbered bookmark (1-9) on a message, clearing it from any other message when setting"
    return await call_endpa('bookmark_', dname, json=True, id=id, n=n)

# %% ../nbs/00_core.ipynb #334395f8
async def toggle_comment(
    id:str, # id of code message (or comma-separated ids) to toggle comments on
    dname:str='' # Dialog to toggle comments in; defaults to current dialog. (Note dialog *must* be running for this function)
) -> dict:
    "Toggle line comments on code message(s). If any lines are uncommented, comments all; otherwise uncomments all."
    ids = id
    id,*_ = ids.split(',')
    res = await call_endpa('toggle_comment_', dname, ids=ids, id=id)
    return _check_res(res, dname)

# %% ../nbs/00_core.ipynb #1827e124
async def url2note(
    url:str, # URL to read
    extract_section:bool=True, # If url has an anchor, return only that section
    selector:str=None, # Select section(s) using BeautifulSoup.select (overrides extract_section)
    ai_img:bool=True, # Make images visible to the AI
    split_re:str='' # Regex to split content into multiple notes, set to '' for single note
):
    "Read URL as markdown, and add note(s) below current message with the result"
    res = read_url(url, as_md=True, extract_section=extract_section, selector=selector, ai_img=ai_img)
    if split_re: return [await add_msg(s) for s in re.split(split_re, res, flags=re.MULTILINE)[::-1] if s.strip()]
    return await add_msg(res)


# %% ../nbs/00_core.ipynb #f26259cf
async def create_or_run_dialog(
    name:str, # Name/path of the dialog (relative to current dialog's folder, or absolute if starts with '/')
    template:bool=True, # Include TEMPLATE.ipynb files when creating a new dialog
):
    "Create a new dialog, or set an existing one running"
    name = find_dname(name).lstrip('/')
    return await call_endpa('create_dialog_', name=name, template=template, json=True)

# %% ../nbs/00_core.ipynb #80433dd1
async def stop_dialog(
    name:str, # Name/path of the dialog (relative to current dialog's folder, or absolute if starts with '/')
):
    "Stop a running dialog kernel"
    name = find_dname(name).lstrip('/')
    return await call_endpa('stop_kernel_', name=name, json=True)

# %% ../nbs/00_core.ipynb #62101e04
async def load_dialog(
    src_dname:str, # Dialog to load code from (path relative to solveit data dir, no .ipynb)
    dname:str='', # Target dialog; defaults to current dialog
):
    "Run all code messages from `src_dname` into the target dialog's kernel and return dialog contents."
    unlock = getattr(get_ipython().kernel, 'unlock', None)
    if unlock: unlock()
    return _lt.FullResponse(await call_endpa('load_dialog_', dname, src_dname=src_dname))

# %% ../nbs/00_core.ipynb #e393f14b
async def rm_dialog(
    name:str, # Name/path of the dialog to delete (relative to current dialog's folder, or absolute if starts with '/')
):
    "Delete a dialog (or folder) and associated records, stopping the kernel if running"
    name = find_dname(name).lstrip('/')
    return await call_endpa('rm_dialog_', name=name, sess='{}', json=True)

# %% ../nbs/00_core.ipynb #5617305b
async def run_code_interactive(
    code:str # Code to have user run
):
    """Insert code into user's dialog and request for the user to run it. Use other functions where possible, 
    but if they can not find needed information, *ALWAYS* use this instead of guessing or giving up.
    IMPORTANT: This tool is TERMINAL - after calling it, you MUST stop all tool usage 
    and wait for user response. Never call additional tools after this one."""
    await add_msg('# Please run this:\n'+code, msg_type='code')
    return {'success': "CRITICAL: Message added to user dialog. STOP IMMEDIATELY. Do NOT call any more tools. Wait for user to run code and respond."}

# %% ../nbs/00_core.ipynb #5250fa23
_msg_edit_doc = f"""
Be sure you've called `view_msg(…)` to ensure you know the line nums.

Message editing standard parameters:

id: Message id to edit, or list of ids, or 'all' for all messages in dialog
dname: Dialog to get info for; defaults to current dialog
update_output: If True, replace in output instead of content
log_changed: Add a note showing the deleted content?

returns:
- For single id: diff of changes, or "none: No changes.", or "error: ..."
- For id list (or 'all'): list of tuples of (id,diff) for changed messages"""

# %% ../nbs/00_core.ipynb #ee87e70d
def _msg_edit(f, name=None):
    async def wrapper(id:str|list[str], *args, update_output:bool=False, dname:str='', log_changed:bool=False, **kw):
        async def _one(mid):
            msg = await read_msg(n=0, id=mid, dname=dname)
            field = 'output' if update_output else 'content'
            text = msg.get(field, '')
            if not text: return f"error: Message has no {field}"
            try: new_text = await maybe_await(f(text, *args, **kw))
            except ValueError as e: return f'error: {e}'
            await update_msg(id=mid, **{field: new_text}, dname=dname, log_changed=log_changed)
            diff = '\n'.join(list(difflib.unified_diff(text.splitlines(), new_text.splitlines(), n=1, lineterm=''))[2:])
            return diff or 'none: No changes.'
        if isinstance(id, list) or id == 'all':
            if id=='all': id = [m['id'] for m in (await find_msgs(dname=dname, include_meta=False, include_output=False))]
            return [(mid, r) for mid in id if not (r:=await _one(mid)).startswith(('error:', 'none:'))]
        return await _one(id)
    res = splice_sig(wrapper, f, 'text')
    if name: res.__name__ = res.__qualname__ = name
    res.__doc__ = (f.__doc__ or '') + _msg_edit_doc
    return res

# %% ../nbs/00_core.ipynb #ceb1ad3b
def _insert_line(
    text:str,
    insert_line:int, # The 1-based line number after which to insert the text (0: before 1st line, 1: after 1st line, 2: after 2nd, etc.)
    new_str:str, # The text to insert
):
    "Insert new_str at specified line number"
    lines = text.splitlines()
    if not (0 <= insert_line <= len(lines)): raise ValueError(f'Invalid line {insert_line}. Valid range: 0-{len(lines)}')
    lines.insert(insert_line, new_str)
    return '\n'.join(lines)

msg_insert_line  = _msg_edit (_insert_line, 'msg_insert_line')

# %% ../nbs/00_core.ipynb #e6b2a19b
def _str_replace(
    text:str,
    old_str:str, # Text to find and replace
    new_str:str, # Text to replace with
    start_line:int=None, # Optional 1-based start line to limit search
    end_line:int=None, # Optional 1-based end line to limit search
    n_matches:int=None, # Max replacements (None=all)
    re_filter:str=None, # If provided, only process lines matching this regex (like g// in ex)
    invert_filter:bool=False, # Invert the filter (like g!// in ex)
):
    "Replace occurrence(s) of old_str with new_str"
    def _repl(s, label=''):
        if s.count(old_str) == 0: raise ValueError(f"Text not found{label}: {repr(old_str)}")
        return s.replace(old_str, new_str) if n_matches is None else s.replace(old_str, new_str, n_matches)
    if re_filter or start_line or end_line:
        lines = text.splitlines(True)
        s,e = (start_line or 1)-1, end_line or len(lines)
        if not re_filter: return ''.join(lines[:s]) + _repl(''.join(lines[s:e]), f' in lines {s+1}-{e}') + ''.join(lines[e:])
        pat = re.compile(re_filter)
        matched = [i for i in range(s,e) if bool(pat.search(lines[i])) != invert_filter]
        if not matched: return text
        for i in matched: lines[i] = _repl(lines[i], f' on line {i+1}')
        return ''.join(lines)
    return _repl(text)

msg_str_replace =  _msg_edit (_str_replace, 'msg_str_replace')

# %% ../nbs/00_core.ipynb #983ce14a
def _strs_replace(
    text:str,
    old_strs:list[str], # List of strings to find and replace
    new_strs:list[str], # List of replacement strings (must match length of old_strs)
    start_line:int=None, # Optional 1-based start line to limit search
    end_line:int=None, # Optional 1-based end line to limit search
    n_matches:int=None, # Max replacements per string (None=all)
    re_filter:str=None, # If provided, only process lines matching this regex (like g// in ex)
    invert_filter:bool=False, # Invert the filter (like g!// in ex)
):
    "Replace multiple strings simultaneously"
    if not isinstance(old_strs, list): raise ValueError(f"`old_strs` should be a list[str] but got {type(old_strs)}")
    if not isinstance(new_strs, list): raise ValueError(f"`new_strs` should be a list[str] but got {type(new_strs)}")
    if len(old_strs) != len(new_strs): raise ValueError(f"Length mismatch: {len(old_strs)} old_strs vs {len(new_strs)} new_strs")
    for idx,(old_str,new_str) in enumerate(zip(old_strs, new_strs)):
        text = _str_replace(text, old_str, new_str, start_line=start_line, end_line=end_line,
                            n_matches=n_matches, re_filter=re_filter, invert_filter=invert_filter)
    return text

msg_strs_replace =  _msg_edit (_strs_replace, 'msg_strs_replace')

# %% ../nbs/00_core.ipynb #7b11e714
def _norm_lines(n:int, start:int, end:int=None):
    "Normalize and validate line range. Returns (start, end) or raises ValueError."
    if end is None: end = start
    if end < 0: end = n + end + 1
    if not (1 <= start <= n): raise ValueError(f'Invalid start line {start}. Valid range: 1-{n}')
    if not (start <= end <= n): raise ValueError(f'Invalid end line {end}. Valid range: {start}-{n}')
    return start, end

# %% ../nbs/00_core.ipynb #1002423f
def _replace_lines(
    text:str,
    start_line:int, # Starting line number to replace (1-based indexing)
    end_line:int=None, # Ending line number to replace (1-based, inclusive, negative counts from end, None for single line)
    new_content:str='', # New content to replace the specified lines
):
    "Replace line range with new content"
    lines = text.splitlines(keepends=True)
    s,e = _norm_lines(len(lines), start_line, end_line)
    if lines and new_content and not new_content.endswith('\n'): new_content += '\n'
    lines[s-1:e] = [new_content] if new_content else []
    return ''.join(lines)

msg_replace_lines =  _msg_edit (_replace_lines, 'msg_replace_lines')

# %% ../nbs/00_core.ipynb #cbd87701
def _del_lines(
    text:str,
    start_line:int, # Starting line number to delete (1-based indexing)
    end_line:int=None, # Ending line number to delete (1-based, inclusive, negative counts from end, None for single line)
    re_filter:str=None, # If provided, only delete lines matching this regex (like g// in ex)
    invert_filter:bool=False, # Invert the filter (like g!// in ex)
):
    "Delete line range"
    lines = text.splitlines(keepends=True)
    s,e = _norm_lines(len(lines), start_line, end_line)
    if re_filter:
        pat = re.compile(re_filter)
        matched = {i for i in range(s-1,e) if bool(pat.search(lines[i])) != invert_filter}
        if not matched: return text
        lines = [l for i,l in enumerate(lines) if i not in matched]
    else: del lines[s-1:e]
    return ''.join(lines)

msg_del_lines =  _msg_edit (_del_lines, 'msg_del_lines')

# %% ../nbs/00_core.ipynb #73cb7c93
async def _python_edit(
    text:str,
    code:str, # Python code; `text` var has content, last expr is new content
):
    "Edit text by running `code` in python. `text` var has content, last expr is new content"
    res = await python(f'text = {repr(text)}\n{code}')
    return res

msg_python =  _msg_edit (_python_edit, 'msg_python')

# %% ../nbs/00_core.ipynb #11ee26d9
def solveit_docs():
    """Full reference documentation for Solveit - use this to answer questions about how to use Solveit.
    **NB**: The whole docs fit in LLM context, so read the whole thing, don't search/filter it. *Always* re-run rather than relying on truncated history or assumptions."""
    _ref_gist_id = '9e7b444aba5ecf6d14295ba2cee890c3'
    pre = f"""⚠️ This content will be truncated in your next turn. Re-call this function if you need it again.
If the user wants more info, give them a link to https://gist.github.com/jph00/{_ref_gist_id}."""
    return pre + gist_file(_ref_gist_id)['content']

# %% ../nbs/00_core.ipynb #70ec67db
def dialog_link(
    dname:str='', # Dialog to link to (relative to current dialog's folder, or absolute if starts with '/'); empty for in-page anchor link
    msg_id:str=None # Optional message id to scroll to
):
    """Return an IPython HTML link to open a dialog in Solveit.
    After calling this, output the resulting HTML anchor tag exactly as returned—do not wrap in a fenced code block or convert to markdown link format."""
    if not (dname or msg_id): return 'err: no dname or msg_id'
    url = ''
    if dname:
        dname = find_dname(dname).removeprefix('/')
        url += f"/dialog_?{urlencode({'name': dname})}"
    if msg_id: url += f"#{msg_id}"
    return HTML(f'<a href="{url}" target="_blank">{dname}</a>') if dname else Markdown(f'[{url}]({url})')


# %% ../nbs/00_core.ipynb #c147990d
async def spawn_agent(prompt:str):
    """Spawn a subagent to complete a task defined by `prompt`. Must be run as a tool - not from Python.
    The subagent's context and tools is defined by the parent prompt's history"""
    raise Exception("Do not run from python: this is a server-side only tool")

# %% ../nbs/00_core.ipynb #d7027cfb
async def search(q:str):
    "Get search results for a query and return as text"
    return await call_endpa('search_', json=True, q=q, timeout=60)

# %% ../nbs/00_core.ipynb #0f17ca2c
async def searches(searches:list[str]):
    "Get search results for multiple queries in parallel"
    return await call_endpa('searches_', json=True, searches=searches, timeout=60)

# %% ../nbs/00_core.ipynb #84816ccc
async def web_answer(
    pr:str, # The prompt - i.e the question to get answered
    qs:list[str], # A list of 1 or more web search queries that might provide useful results. Do not constrain the queries too much - make sure the agent as a range of links to choose from
    page_chars:int=50000 # Truncate web pages beyond this size
): # Markdown text of the answer, with sources as appropriate
    "Use a search agent to search for all of `qs`, choose suitable pages to read, and answer `pr` based on the page contents."
    return await call_endpa('web_answer_', json=True, pr=pr, qs=qs, page_chars=page_chars, timeout=60)
