# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_exhash.ipynb.

# %% auto #0
__all__ = ['msg_lnhashview', 'msg_exhash']

# %% ../nbs/04_exhash.ipynb #d6291515
from fastcore.utils import *
from .core import *
from exhash import *

# %% ../nbs/04_exhash.ipynb #c7a53c95
async def msg_lnhashview(
    id:str, # id of message to view
    dname:str='', # Dialog containing message; defaults to current dialog
    start:int=None, # Starting line (1-based) to view (defaults to 1st line if None)
    end:int=None, # End line (defaults to last line if None)
) -> str:
    "Show lnhash-addressed lines of a message"
    msg = await read_msgid(id=id, dname=dname)
    if not msg: return 'No such message.'
    return PrettyString('\n'.join(lnhashview(msg['content'], start=start, end=end)))

# %% ../nbs/04_exhash.ipynb #9bdae034
async def msg_exhash(
    id:str, # id of message to edit
    cmds:list, # List of exhash command tuples to apply
    dname:str='', # Dialog containing message; defaults to current dialog
) -> str:
    """Verified line-addressed editor. Apply command tuples to msg `id` contents, return lnhash diff.
    **NB**: every command is a tuple whose first element is an address string.
    **NB**: hashes are checked against the current text immediately before each command runs; order commands last->first.

    Use `msg_lnhashview(id)` to get hash-verified addresses before first use.

    Address strings:
        Single:   ``12|a3f2|``
        Range:    ``12|a3f2|,15|b1c3|``
        Last:     ``$`` (last line)
        Whole:    ``%`` (whole file, same as ``1,$``)
        Special:  ``0|0000|`` targets before line 1 (only with a or i)

    Command tuples:
        (addr, "s", pattern, replacement[, flags])
                           Substitute (Rust regex syntax). Replacement supports $1, $0, ${name}.
                           Flags: g=all, i=case-insensitive. args may contain literal / & newlines
        (addr, "d")        Delete line(s)
        (addr, "a", text)  Append payload after line
        (addr, "i", text)  Insert payload before line
        (addr, "c", text)  Change/replace with payload
        (addr, "j")        Join with next line; with range, joins all
        (addr, "m", dest)  Move line(s) after dest address
        (addr, "t", dest)  Copy line(s) after dest address
        (addr, ">", n)     Indent n levels (default 1, 4 spaces each)
        (addr, "<", n)     Dedent n levels (default 1)
        (addr, "sort")     Sort lines alphabetically
        (addr, "p")        Print (include in output without changing)
        (addr, "g", payload), (addr, "g!", payload), (addr, "v", payload)
                           Global commands; payload uses compact ex syntax such as ``/pattern/d``
        (addr, "y", payload) Transliterate; payload uses compact ex syntax such as ``/abc/ABC/``

    `cmds` is a required list of command tuples. Text fields may contain newlines, including
    multiline a/i/c payloads and s pattern/replacement fields; payloads are inserted literally.
    Do NOT add a trailing `.` line — the string boundary ends the block. A trailing `.` will be inserted literally (with a warning)."""
    msg = await read_msgid(id=id, dname=dname)
    if not msg: return 'No such message.'
    txt = msg['content']
    edit = exhash(txt, cmds)
    res = '\n'.join(edit['lines'])
    upres = await update_msg(id=id, content=res, dname=dname)
    assert upres.startswith('_'), f"Message update failed: {upres}"
    return edit.format_diff()
