"""Run a prompt in the current kernel.

Docs: https://AnswerDotAI.github.io/dialoghelper/prompt.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_prompt.ipynb.

# %% auto #0
__all__ = ['py_tool', 'spawn_tool', 'prepare_prompt_context', 'public_error_msg', 'run_prompt']

# %% ../nbs/08_prompt.ipynb #747df9fb
import os, json, sys, asyncio, base64
from contextlib import aclosing
from datetime import datetime
from pathlib import Path
from inspect import isawaitable
from IPython import get_ipython
from IPython.display import display, Markdown
from IPython.utils.capture import capture_output
from fastcore.foundation import L
from fastcore.xtras import obj2dict, dict2obj
from fastcore.nbio import dict2nb, repair_nb
from fastcore.xml import ft, to_xml, Variable_Errors, Tool_Errors, Context_Warning, Safe
from fastllm.chat import AsyncChat, StreamAccum
from aidialog.msg_parts import mk_msgs, ToolResponse, StopResponse, MdStr
from fasttransport.core import AsyncTransport
from aidialog.dialog import Message, sprompt, prompt_output, get_output_mds, INTERRUPTED, scode
from aidialog.hist import chat2dlg, get_exprs, get_refs, is_nameerr, vars_hist, warning_tag, output_parts, merge_media
import aidialog.ipynb
from .core import cells_client, _add_msg_unsafe

# %% ../nbs/08_prompt.ipynb #e361e988
def _prompt_body(cells, id):
    "Select a stored prompt and its preceding history without changing the snapshot."
    for i,cell in enumerate(cells):
        if cell['id'] != id: continue
        if not cell['metadata'].get('solveit_ai'): raise ValueError(f'cell {id} is not a prompt')
        return dict(cells=obj2dict(cells[:i]), prompt=obj2dict(cell) | dict(outputs=[]))
    raise KeyError(f'prompt {id} no longer exists')

# %% ../nbs/08_prompt.ipynb #7e1f84c7
def _craft_messages(files, name):
    msgs,errors = [Message('# Loaded CRAFTs.', msg_type='note', id='_crafts_h1')],[]
    for f in files:
        if f['path']==name: continue
        try:
            nb = json.loads(f['content'])
            repair_nb(nb)
            cells = dict2nb(nb).cells
        except ValueError as e:
            errors.append(f'Could not read {f["path"]}: {e}')
            continue
        cid = f'_craft_{hash(f["path"]) & 0xffffffff:08x}'
        msgs.append(Message(f'<craft-block from-dialog="/{f["path"]}">', msg_type='raw', id=cid))
        msgs.extend(Message.from_cell(c) for c in cells)
        msgs.append(Message('</craft-block>', msg_type='raw', id=cid+'_end'))
    msgs.append(Message('End of CRAFTs.', msg_type=sprompt, output=prompt_output('Ok!'), id='_craft_end'))
    for m in msgs: m.pinned = True
    return msgs,errors

# %% ../nbs/08_prompt.ipynb #7020e817
async def _lp_get(path):
    "GET a Solve-LP route with the kernel's credentials"
    headers = {'Authorization':f'Bearer {os.environ["AAI_USER_KEY"]}', 'X-SolveIt-Instance-Id':os.environ['INSTANCE_ID']}
    return await AsyncTransport().request('GET', os.environ['SOLVELP_URL'].rstrip('/')+path, headers=headers)

async def _resolve_refs(msgs, icl_refs, eval_exprs=None, get_schemas=None):
    "Values, schemas and errors for the `$`, `!` and `&` references in `msgs` and the ICL preamble"
    vs = get_exprs(msgs) + [v for v in icl_refs.get('exprs', []) if v not in get_exprs(msgs)]
    cmds = get_exprs(msgs, sigil='!') + icl_refs.get('cmds', [])
    cmd_exprs = {c:f'get_ipython().getoutput({c!r}).n' for c in cmds}
    eval_exprs = eval_exprs or get_ipython().eval_exprs
    ns = await eval_exprs(vs=vs + list(cmd_exprs.values())) or {}
    if isinstance(ns, str): raise RuntimeError(f'eval_exprs: {ns}')
    undefined = [v for v in vs if is_nameerr(ns.get(v))]
    ns = {v:ns[v] for v in vs if v in ns and v not in undefined} | {f'!`{c}`':ns[e] for c,e in cmd_exprs.items() if e in ns}
    ns = {k:(dict(__bytes__=base64.b64encode(v).decode()) if isinstance(v, bytes) else v) for k,v in ns.items()}
    texts = L(msgs).flatmap(lambda m: [m.content] if m.msg_type in ('prompt','note') else get_output_mds(m.output))
    ts = L(get_refs(' '.join(texts), '&') or []) + icl_refs.get('tools', [])
    ts = [t for t in ts.unique() if t not in ('py','python','spawn_agent')]
    get_schemas = get_schemas or get_ipython().get_schemas
    schema_res = get_schemas(fs=ts)
    if isawaitable(schema_res): schema_res = await schema_res
    if isinstance(schema_res, str): raise RuntimeError(f'get_schemas: {schema_res}')
    schemas = [o for o in schema_res.values() if not isinstance(o, str)]
    errors = [o for o in schema_res.values() if isinstance(o, str)]
    return ns, schemas, dict(vars=undefined, tools=errors)

async def prepare_prompt_context(data, id, fc, *, inc_craft=True, icl_refs=None, solveit=None, eval_exprs=None, get_schemas=None):
    "Assemble a stored prompt's request body for Solve-LP's Solveit policy; namespace lookups default to the active kernel"
    solveit = solveit or {}
    body = _prompt_body(data['cells'], id)
    body['prompt']['metadata'].pop('skipped', None)
    opts = solveit.get('defaults', {}) | data.get('metadata', {}).get('solveit', {})
    opts |= {k:solveit[k] for k in ('math_mode', 'today') if k in solveit}
    crafts,craft_errors = [],[]
    if inc_craft:
        files = await fc.search(path=str(Path(data['path']).parent), up='CRAFT.ipynb', fields='content')
        crafts,craft_errors = _craft_messages(files['files'][::-1], data['path'])
    craft_errors += [e for e in solveit.get('craft_errors') or [] if e]
    messages = crafts + [Message.from_cell(c) for c in body['cells']] + [Message.from_cell(body['prompt'])]
    visible = [m for m in messages if not m.skipped]
    ns,schemas,errors = await _resolve_refs(visible, icl_refs or {}, eval_exprs, get_schemas)
    dialog = dict(path=data['path'], opts=opts, ns=ns, schemas=schemas, errors=errors | dict(crafts=craft_errors),
        py_version=f'{sys.version_info.major}.{sys.version_info.minor}')
    return dict(cells=obj2dict([m.to_cell() for m in messages[:-1]]), prompt=body['prompt'], dialog=dialog)

# %% ../nbs/08_prompt.ipynb #200e8410
_py_desc = "Run Python/IPython code in the client's persistent execution environment. Variables and imports persist across calls."
_py_params = dict(type='object', properties=dict(code=dict(type='string', description='Python/IPython code to run')), required=['code'], additionalProperties=False)
py_tool = dict(type='function', name='py', description=_py_desc, parameters=_py_params, strict=True)

_spawn_desc = ("Spawn a subagent to complete a task defined by `prompt`. The subagent sees the dialog history "
    "above the current prompt; its reply returns only to the calling model, not the user. Use sparingly, for "
    "discrete tasks whose full working does not need to stay in context.")
_spawn_params = dict(type='object', properties=dict(prompt=dict(type='string', description='The task for the subagent to complete')), required=['prompt'], additionalProperties=False)
spawn_tool = dict(type='function', name='spawn_agent', description=_spawn_desc, parameters=_spawn_params, strict=True)

# %% ../nbs/08_prompt.ipynb #db4794fa
def _tool_text(res):
    "The model-facing text for a `py` return value, keeping any marker type"
    if res is None: return ''
    if isinstance(res, Markdown): return MdStr(res.data)
    return res if isinstance(res, str) else repr(res)

def _tool_result(res, cap, aim_info=None):
    "Format a sandboxed call's return value and captured output for the model"
    if isinstance(res, ToolResponse): return res
    outs = [dict(output_type='stream', name=n, text=t) for n,t in (('stdout',cap.stdout), ('stderr',cap.stderr)) if t]
    outs += [dict(output_type='display_data', data=o.data, metadata=o.metadata) for o in cap.outputs]
    val = _tool_text(res)
    if val: outs.append(dict(output_type='execute_result', data={'text/plain':val}, metadata={}))
    m = Message('', msg_type=scode, output=outs)
    merged = merge_media(m.ai_output, output_parts(m, aim_info))
    if not isinstance(merged, str): return merged
    return type(val)(merged or 'No output')

async def _run_py(code, aim_info=None, after=None):
    "Run one `py` tool call in the sandbox; a denial adds the code after message `after` for the user to run"
    ns = get_ipython().user_ns
    sandbox = ns.get('py') or ns['python']
    try:
        with capture_output() as cap: res = await sandbox(code)
    except PermissionError as e:
        if after: await _add_msg_unsafe(code, id=after, msg_type=scode)
        return StopResponse(f"PermissionError: {e}. Code message has been added to dialog. Ask user to run it.")
    return _tool_result(res, cap, aim_info)

# %% ../nbs/08_prompt.ipynb #be3f4bc0
def _dlg_chat(model, tools=None, ns=None):
    "An `AsyncChat` against Solve-LP's dialog route, connected with the kernel's environment"
    return AsyncChat(model, api_name='openai', base_url=os.environ['SOLVELP_URL'].rstrip('/'), endpoint='/dlg_responses',
        api_key=os.environ['AAI_USER_KEY'], tools=tools, ns=ns, use_previous_response_id=True,
        extra_headers={'X-SolveIt-Instance-Id':os.environ['INSTANCE_ID']}, prompt_cache_key=os.environ.get('RUSTYGATE_KERNEL_ID'))

_spawn_pre = "<system>You are a spawned agent. Your reply goes only to the calling model, never the user, so answer the task fully and directly.</system>\n"

async def _run_spawn(model, body, py, prompt, think=None):
    "Answer `prompt` as a spawned agent over the prepared turn `body`"
    chat = _dlg_chat(model, [py_tool], dict(py=py))
    pcell = Message(_spawn_pre+prompt, msg_type=sprompt, id='spawn').to_cell()  # a fixed id: the cell exists only inside this one request
    sbody = body | dict(cells=[*body['cells'], body['prompt']], prompt=pcell)
    rs = await chat(stream=True, max_steps=40, think=think, parallel_tool_calls=True, initial_body=sbody)
    async for o in rs: pass
    return chat.full()

# %% ../nbs/08_prompt.ipynb #357c013f
def _err_info(e):
    if getattr(e, 'message', None): return e.message
    if getattr(e, 'args', None): return e.args[0]
    return 'unknown error'

def public_error_msg(e):
    "User-facing text for a failed model request"
    info = _err_info(e)
    sc = getattr(e, 'status_code', 0) or 0
    if getattr(e, 'retryable', False) or sc in (408, 409, 429) or sc >= 500:
        return "The currently selected model is experiencing issues. If this keeps happening, please try again later, and try a different model in the meantime."
    if 'media_type' in str(info).lower(): return "The current model doesn't support that media type."
    return f"Whoops! An error ({info}) occurred while processing your request.\nIf this problem persists, please contact us on Discord.\nPlease include your dialog url and error info in your message."

def _note(text, note):
    "`text` with `note` appended, or the note alone for an empty reply"
    return f"{text.rstrip()}\n\n{note}" if text.strip() else note

# %% ../nbs/08_prompt.ipynb #f3105207
async def _prompt_model_info(model):
    catalog = await _lp_get('/models')
    info = next((m for m in catalog['data'] if m['id']==model), None)
    if info is None: raise ValueError(f'Unsupported model: {model!r}')
    mods = set(info['input_modalities'])
    return info | dict(supports_vision='image' in mods, supports_video_input='video' in mods,
        supports_audio_input='audio' in mods, supports_pdf_input='pdf' in mods)

# %% ../nbs/08_prompt.ipynb #da6eb458
async def run_prompt(
    prompt=None, # Prompt text; omit when passing a stored cell id
    *,
    model, # Solve-LP model id
    think=None, # Reasoning effort accepted by fastllm
    id=None, # Read this prompt and its history when execution starts
    solveit=None, # Solveit settings for the policy (`defaults`, `math_mode`, `craft_errors`, `today`); requires id
    inc_craft=True, # Include inherited CRAFT context and startup warnings
):
    "Prepare and stream one prompt in the kernel, running its tool calls in place."
    if (prompt is None) == (id is None): raise ValueError('Pass prompt text or a prompt cell id, not both')
    if solveit is not None and id is None: raise ValueError('Solveit policy requires a stored prompt id')
    info = await _prompt_model_info(model)
    if id is None: body = dict(cells=[], prompt=obj2dict(Message(prompt, msg_type=sprompt).to_cell()))
    else:
        fc = cells_client()
        data = await fc.view(fields='*,meta')
        if solveit is None:
            body = _prompt_body(data['cells'], id)
            skipped = body['prompt']['metadata'].pop('skipped', None)
        else:
            skipped = next(c for c in data['cells'] if c['id']==id)['metadata'].get('skipped')
            body = await prepare_prompt_context(data, id, fc, inc_craft=inc_craft, icl_refs=await _lp_get('/dlg_policy'), solveit=solveit)
        if skipped: await fc.apply([dict(op='merge', id=id, metadata=dict(skipped=None))])
    async def py(code): return await _run_py(code, info, after=id)
    async def spawn_agent(prompt): return await _run_spawn(model, body, py, prompt, think)
    chat = _dlg_chat(model, [py_tool, spawn_tool], dict(py=py, spawn_agent=spawn_agent))
    rs = await chat(stream=True, think=think, max_steps=40, parallel_tool_calls=True, initial_body=body)
    acc,meta = StreamAccum(chat),dict(is_ai_res=True)
    handle = display(raw=True, metadata=meta, display_id=True)
    def show(text):  # round-trip stray surrogates so ZMQ's utf-8 packer can't choke on them
        handle.update({'text/markdown':text.encode('utf-16', 'surrogatepass').decode('utf-16')}, raw=True, metadata=meta)
    try:
        async with aclosing(rs):
            async for item in rs:
                if acc(item): show(acc.txt)
        text = chat.full() + chat.use.fmt()
    except (KeyboardInterrupt, asyncio.CancelledError): text = _note(acc.txt, INTERRUPTED)
    except Exception as e: text = _note(acc.txt, public_error_msg(e))
    show(text)
