"""Run dialogs' code messages through a live solveit, `nbdev-test`-style

`solveit-test` tests notebooks through a running solveit instance. It uses solveit's runloop and dialog kernels, with current-message tracking and dialog context. `nbdev-test` uses execnb outside solveit, where these features aren't available. Use `solveit-test` for notebooks that depend on them, such as dialoghelper's own.

`solveit-test` requires a running solveit instance. The notebooks must be under the directory that instance serves. The command maps file paths to dialog names and tests notebooks concurrently.

The command uses aidialog's `Dialog.select_msgs`, matching `Dialog.execute`. It selects code messages, never prompts, with these exclusions:

- `skip_exec: true` in frontmatter skips the notebook.
- `eval: false` in a cell directive or metadata skips the cell.
- `nbdev_export` cells never run.

Testing restarts each dialog's kernel, including dialogs you have open in solveit. You lose their existing kernel state. Runs change messages and outputs on disk. Use a clean checkout and review the diff afterward.

A kernel crash or queue problem can prevent a selected message from executing. Its stored output can still contain an error from an earlier run. The report cannot distinguish that error from a new one. Use `--save` to clear the selected messages' outputs before running them.

Docs: https://AnswerDotAI.github.io/dialoghelper/test.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/07_test.ipynb.

# %% auto #0
__all__ = ['test_dlg', 'test_nbs', 'solveit_test']

# %% ../nbs/07_test.ipynb #cb0505ba
import asyncio, sys, time
from fastcore.utils import *
from fastcore.script import call_parse
from fastcore.parallel import parallel_async,num_cpus
from .core import *

# %% ../nbs/07_test.ipynb #321d2cf2
async def test_dlg(
    dname:str, # Name/path of the dialog (relative to current dialog's folder, or absolute if starts with '/')
    ids:list=None, # Message ids to run (default: all code messages, including those hidden from the AI)
    timeout:int=600, # Max seconds to wait for the run to finish
    poll:float=0.5, # Seconds between completion checks
    save:bool=False, # Empty stored outputs of the messages to run first, so results reflect only this run?
)->list[dict]: # Run messages left with error outputs (empty means the dialog passed)
    "Restart `dname`'s kernel, run its code messages through the solveit runloop, and return those that errored"
    await restart_dialog(dname)
    if ids is None:
        msgs = await find_msgs(msg_type='code', context=0, include_output=False, include_meta=False, include_skipped=True, dname=dname)
        ids = [m.id for m in msgs]
    if not ids: return []
    if save: await cells_client(dname).apply([dict(op='update', id=i, outputs=[]) for i in ids])
    await run_msg(','.join(ids), dname=dname)
    end = time.time()+timeout
    for i in ids:
        while (await read_msgid(i, dname=dname)).get('run', False):
            if time.time()>end: raise TimeoutError(f'{dname}: still running after {timeout}s, at message {i}')
            await asyncio.sleep(poll)
    errs = await find_msgs(msg_type='code', only_err=True, context=0, include_skipped=True, dname=dname)
    return [m for m in errs if m.id in set(ids)]

# %% ../nbs/07_test.ipynb #24b935f6
def _runnable_ids(path):
    "Message ids a non-interactive run executes, or None when the whole dialog is skipped"
    from nbdev.frontmatter import nb_frontmatter
    from aidialog.ipynb import read_ipynb
    d = read_ipynb(path)
    if d is None: return None
    if str2bool(nb_frontmatter(d).get('skip_exec', False)): return None
    return [m.id for m in d.select_msgs(all=True)]

# %% ../nbs/07_test.ipynb #3d4119a0
async def test_nbs(
    path:str='.', # An .ipynb file, or a directory of them, to test
    timeout:int=600, # Max seconds to wait per dialog
    keep:bool=False, # Leave dialog kernels running after their test?
    n_workers:int=None, # Max dialogs tested concurrently (default: min(num_cpus(), 8))
    save:bool=False, # Empty stored outputs of the messages to run first, so results reflect only this run?
)->dict: # Failures per notebook name: erroring message ids, or a repr'd exception
    "Test each notebook under `path` as a dialog on the local solveit instance, printing progress `nbdev-test`-style"
    root = data_root()
    p = Path(path)
    files = sorted(p.glob('*.ipynb')) if p.is_dir() else [p]
    if n_workers is None: n_workers = min(num_cpus(), 8)
    failed = {}
    async def _one(f):
        ids = _runnable_ids(f)
        if ids is None: return print(f'skip: {f.name}')
        dname = '/'+str(f.resolve().relative_to(root))
        try:
            errs = await test_dlg(dname, ids=ids, timeout=timeout, save=save)
            if errs: failed[f.name] = [m.id for m in errs]
        except Exception as e: failed[f.name] = [repr(e)]
        finally:
            if not keep: await stop_dialog(dname)
        print(f"{'FAIL' if f.name in failed else 'ok'}: {f.name}")
    await parallel_async(_one, files, n_workers=n_workers)
    return failed

# %% ../nbs/07_test.ipynb #8814e977
@call_parse(pos=['path'])
async def solveit_test(
    path:str='.', # An .ipynb file, or a directory of them, to test
    timeout:int=600, # Max seconds to wait per dialog
    keep:bool=False, # Leave dialog kernels running after their test?
    n_workers:int=None, # Max dialogs tested concurrently (default: min(num_cpus(), 8))
    save:bool=False, # Empty stored outputs of the messages to run first, so results reflect only this run?
):
    "Run notebooks as dialogs on the local solveit instance, `nbdev-test`-style; they must live under its data path"
    failed = await test_nbs(path, timeout=timeout, keep=keep, n_workers=n_workers, save=save)
    if failed:
        sys.stderr.write('\nsolveit-test failed on:\n'+'\n'.join(f'\t{k}: {", ".join(v)}' for k,v in failed.items())+'\n')
        sys.exit(1)
    print('Success.')
