"""Tools to let Solveit view tmux buffers"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_tmux.ipynb.

# %% auto 0
__all__ = ['default_tmux_lines', 'shell_ret', 'set_default_history', 'pane', 'list_panes', 'panes', 'list_windows', 'windows',
           'list_sessions', 'sessions', 'flatten_dict', 'tmux_tool_info']

# %% ../nbs/03_tmux.ipynb
from fastcore.utils import *
from toolslm.funccall import *
import subprocess

# %% ../nbs/03_tmux.ipynb
def shell_ret(*args, capture_output=True, text=True, shell=True, ret=True, **kwargs):
    "Shortcut for `subprocess.run(shell=True)`"
    o = subprocess.run(*args, shell=shell, text=text, capture_output=capture_output, **kwargs)
    return (o.stdout or o.stderr) if ret else o

# %% ../nbs/03_tmux.ipynb
default_tmux_lines = 500

def set_default_history(n:int):
    'Set the default number of lines to capture from tmux history'
    global default_tmux_lines
    default_tmux_lines = n

# %% ../nbs/03_tmux.ipynb
def pane(
    n:int=None, # Number of scrollback lines to capture, in addition to visible area (None uses default_tmux_lines, which is 500 if not otherwise set)
    pane:int=None,     # Pane number to capture from
    session:str=None,  # Session name to target
    window:int=None    # Window number to target
):
    'Grab the tmux history in plain text'
    if n is None: n = default_tmux_lines
    target = session or ''
    if window is not None: target = f'{target}:{window}' if target else f':{window}'
    if pane is not None: target = f'{target}.{pane}' if target else f'.{pane}'
    cmd = f'tmux capture-pane -p -S -{n}'
    if target: cmd += f' -t {target}'
    return shell_ret(cmd).strip()

# %% ../nbs/03_tmux.ipynb
def list_panes(
    session:str=None,  # Session name to list panes from
    window:int=None    # Window number to list panes from
):
    'List panes for a session/window (or current if none specified)'
    target = session or ''
    if window is not None: target = f'{target}:{window}' if target else f':{window}'
    cmd = f'tmux list-panes{" -t " + target if target else ""}'
    return shell_ret(cmd)

# %% ../nbs/03_tmux.ipynb
def _pane_data(line, n, session, window):
    pane_num = int(line.split(':')[0])
    return (pane_num, pane(n=n, pane=pane_num, session=session, window=window))

def panes(
    session:str=None,  # Session name to target
    window:int=None,   # Window number to target
    n:int=None         # Number of scrollback lines to capture
):
    'Grab history from all panes in a session/window'
    if n is None: n = default_tmux_lines
    panes_info = list_panes(session=session, window=window).strip().split('\n')
    return dict(_pane_data(line, n, session, window) for line in panes_info)

# %% ../nbs/03_tmux.ipynb
def list_windows(
    session:str=None  # Session name to list windows from
):
    'List all windows in a session'
    cmd = f'tmux list-windows{" -t " + session if session else ""}'
    return shell_ret(cmd)

# %% ../nbs/03_tmux.ipynb
def _window_data(line, n, session):
    parts = line.split(':')
    win_num = int(parts[0])
    win_name = parts[1].split('[')[0].strip().rstrip('*-')
    return (f'{win_num}:{win_name}', panes(session=session, window=win_num, n=n))

def windows(
    session:str=None,  # Session name to target
    n:int=None         # Number of scrollback lines to capture
):
    'Grab history from all panes in all windows of a session'
    windows_info = list_windows(session).strip().split('\n')
    return dict(_window_data(line, n, session) for line in windows_info)

# %% ../nbs/03_tmux.ipynb
def list_sessions():
    'List all tmux sessions'
    return shell_ret('tmux list-sessions')

# %% ../nbs/03_tmux.ipynb
def _session_data(line, n):
    session_name = line.split(':')[0]
    return (session_name, windows(session=session_name, n=n))

def sessions(
    n:int=None  # Number of scrollback lines to capture
):
    'Grab history from all panes in all windows of all sessions'
    sessions_info = list_sessions().strip().split('\n')
    return dict(_session_data(line, n) for line in sessions_info)

# %% ../nbs/03_tmux.ipynb
def flatten_dict(d, parent_key='', sep='//'):
    'Flatten nested dict into list of (key_path, value) tuples'
    items = []
    for k, v in d.items():
        new_key = f'{parent_key}{sep}{k}' if parent_key else k
        if isinstance(v, dict): items.extend(flatten_dict(v, new_key, sep))
        else: items.append((new_key, v))
    return items

# %% ../nbs/03_tmux.ipynb
def tmux_tool_info():
    "Add a the message below, showing the available tools, to Solveit"
    add_msg("dialoghelper.tmux tools: &`[pane, list_panes, panes, list_windows, windows, list_sessions, sessions]`")
