"""Docs: https://AnswerDotAI.github.io/dialoghelper/utils.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_utils.ipynb.

# %% auto #0
__all__ = ['md_cls_d', 'msg_ast_replace', 'add_styles', 'ast_py', 'ast_grep', 'ctx_folder', 'ctx_repo', 'ctx_symfile',
           'ctx_symfolder', 'ctx_sympkg', 'import_string', 'mk_toollist', 'import_gist', 'InputBtn', 'input',
           'InputForm']

# %% ../nbs/06_utils.ipynb #4dd4b925
import os,re,inspect,ast,collections,time,asyncio,json,linecache,importlib,difflib,uuid,builtins,subprocess

from typing import Dict
from tempfile import TemporaryDirectory
from ipykernel_helper import *
from dataclasses import dataclass
from os.path import normpath
from fastcore.xml import to_xml
from fastcore.meta import splice_sig, delegates, delegated

from fastcore.utils import *
from fastcore.xtras import asdict
from fastcore.docments import MarkdownRenderer
from ghapi.all import *
from inspect import currentframe,Parameter,signature
from httpx import AsyncClient, get as xget, post as xpost
from IPython.display import display,Markdown,HTML
from monsterui.all import franken_class_map,apply_classes
from toolslm.xml import *
from fasthtml.common import *
from fasthtml.components import Solveit_input
from urllib.parse import urlencode
from safepyrun import RunPython,find_var,create_python_magic,load_ipython_extension
from pyskills import allow
from fastcore.tools import *

from .core import *
from .core import _msg_edit

# %% ../nbs/06_utils.ipynb #c9936691
_lt = import_no_init('fastllm.chat')

# %% ../nbs/06_utils.ipynb #cc9f963f
md_cls_d = {
    **{f'h{i}': f'uk-h{i}' for i in range(1,5)},
    'a': "uk-link",
    'blockquote': "uk-blockquote",
    'hr':'uk-divider-icon',
    'table':'uk-table uk-table-sm uk-table-middle uk-table-divider border [&_tr]:divide-x w-[80%] mx-auto',
    'ol': 'uk-list uk-list-decimal space-y-0', 
    'ul': 'uk-list uk-list-bullet space-y-0',
    'p': 'leading-tight',
    'li': 'leading-tight',
    'pre': '', 'pre code': '',
    'code': 'tracking-tight'
}

def add_styles(s:str, cls_map:dict=None):
    "Add solveit styles to `s`"
    return Safe(apply_classes(s, class_map=cls_map or md_cls_d))

# %% ../nbs/06_utils.ipynb #9adf1cbb
def ast_py(code:str):
    "Get an SgRoot root node for python `code`"
    from ast_grep_py import SgRoot
    return SgRoot(code, "python").root()

# %% ../nbs/06_utils.ipynb #22c2316b
def ast_grep(
    pattern:str, # ast-grep pattern to search, e.g "post($A, data=$B, $$$)"
    path:str=".", # path to recursively search for files
    lang:str="python" # language to search/scan
): # json format from calling `ast-grep --json=compact
    """Use `ast-grep` to find code patterns by AST structure (not text).
    
    Pattern syntax:
    - $VAR captures single nodes, $$$ captures multiple
    - Match structure directly: `def $FUNC($$$)` finds any function; `class $CLASS` finds classes regardless of inheritance
    - DON'T include `:` - it's concrete syntax, not AST structure
    - Whitespace/formatting ignored - matches structural equivalence
    
    Examples: `import $MODULE` (find imports); `$OBJ.$METHOD($$$)` (find method calls); `await $EXPR` (find await expressions)
    
    Useful for: Refactoring—find all uses of deprecated APIs or changed signatures; Security review—locate SQL queries, file operations, eval calls; Code exploration—understand how libraries are used across codebase; Pattern analysis—find async functions, error handlers, decorators; Better than regex—handles multi-line code, nested structures, respects syntax"""
    cmd = f"ast-grep --pattern '{pattern}' --lang {lang} --json=compact"
    if path != ".": cmd = f"cd {path} && {cmd}"
    res = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    return json.loads(res.stdout) if res.stdout else res.stderr

# %% ../nbs/06_utils.ipynb #5880e518
def _ast_replace(
    text:str,
    pattern:str, # AST pattern to match, e.g. 'print($A)'; use $VAR for single nodes, $$$ for multiple
    rewrite:str, # Replacement template with metavariables expanded, e.g. 'log($A)'
    lang:str='python' # Source language (see ast-grep --help for supported languages)
 ):
    """Replace code by AST pattern using ast-grep.

    Pattern syntax:
    - $VAR captures single nodes, $$$ captures multiple
    - Match structure directly: `def $FUNC($$$)` finds any function; `class $CLASS` finds classes regardless of inheritance
    - DON'T include `:` - it's concrete syntax, not AST structure
    - Whitespace/formatting ignored - matches structural equivalence

    Examples: `import $MODULE` (find imports); `$OBJ.$METHOD($$$)` (find method calls); `await $EXPR` (find await expressions)"""
    res = subprocess.run(
        ['ast-grep', 'run', '--pattern', pattern, '--rewrite', rewrite,
         '--lang', lang, '--update-all', '--stdin'],
        input=text, capture_output=True, text=True)
    if res.returncode: raise ValueError(res.stderr.strip())
    if not res.stdout or res.stdout == text: raise ValueError(f"No matches found for pattern: {pattern}")
    return res.stdout

msg_ast_replace  = _msg_edit (_ast_replace, 'msg_ast_replace')

# %% ../nbs/06_utils.ipynb #5fd28219
@delegates(folder2ctx)
async def ctx_folder(
    path:Path='.',  # Path to collect
    types:str|list='py,doc',  # list or comma-separated str of ext types from: py, js, java, c, cpp, rb, r, ex, sh, web, doc, cfg
    out=False, # Include notebook cell outputs?
    raw=True, # Add raw message, or note?
    exts:str|list=None, # list or comma-separated str of exts to include (overrides `types`)
    **kwargs
):
    "Convert folder to XML context and place in a new message"
    if exts: types=None
    res = folder2ctx(path, types=types, out=out, exts=exts, **kwargs)
    if not raw: res = f'```\n{res}\n```'
    return await add_msg(res, msg_type='raw' if raw else 'note')


# %% ../nbs/06_utils.ipynb #2dc4dc40
allow(repo2ctx)

@delegates(repo2ctx)
async def ctx_repo(
    owner:str,  # GitHub repo owner
    repo:str,   # GitHub repo name
    types:str|list='py,doc',  # list or comma-separated str of ext types from: py, js, java, c, cpp, rb, r, ex, sh, web, doc, cfg
    exts:str|list=None, # list or comma-separated str of exts to include (overrides `types`)
    out=False, # Include notebook cell outputs?
    raw=True, # Add raw message, or note?
    **kwargs
):
    "Convert GitHub repo to XML context and place in a new message"
    res = await repo2ctx(owner, repo, out=out, types=types, exts=exts, **kwargs)
    if exts: types=None
    if not raw: res = f'```\n{res}\n```'
    return await add_msg(res, msg_type='raw' if raw else 'note')

# %% ../nbs/06_utils.ipynb #5bd8915b
async def ctx_symfile(sym):
    "Add note with filepath and contents for a symbol's source file"
    return await add_msg(sym2file(sym), msg_type='note');


# %% ../nbs/06_utils.ipynb #bbc9bd0c
@delegates(sym2folderctx)
async def ctx_symfolder(
    sym, # Symbol to get folder context from
    **kwargs):
    "Add raw message with folder context for a symbol's source file location"
    return await add_msg(sym2folderctx(sym, **kwargs), msg_type='raw');


# %% ../nbs/06_utils.ipynb #9d8d83b5
@delegates(sym2folderctx)
async def ctx_sympkg(
    sym, # Symbol to get folder context from
    **kwargs):
    "Add raw message with repo context for a symbol's root package"
    return await add_msg(sym2pkgctx(sym, **kwargs), msg_type='raw');


# %% ../nbs/06_utils.ipynb #1ccfc95a
def import_string(
    code:str, # Code to import as a module
    name:str  # Name of module to create
):
    with TemporaryDirectory() as tmpdir:
        path = Path(tmpdir) / f"{name}.py"
        path.write_text(code)
        # linecache.cache storage allows inspect.getsource() after tmpdir lifetime ends
        linecache.cache[str(path)] = (len(code), None, code.splitlines(keepends=True), str(path))
        spec = importlib.util.spec_from_file_location(name, path)
        module = importlib.util.module_from_spec(spec)
        sys.modules[name] = module
        spec.loader.exec_module(module)
        return module

# %% ../nbs/06_utils.ipynb #27730708
def mk_toollist(syms):
    return "\n".join(f"- &`{sym.__name__}`: {sym.__doc__}" for sym in syms if is_usable_tool(sym))

# %% ../nbs/06_utils.ipynb #4d3e1b46
def import_gist(
    gist_id:str, # user/id or just id of gist to import as a module
    mod_name:str=None, # module name to create (taken from gist filename if not passed)
    add_global:bool=True, # add module to caller's globals?
    import_wildcard:bool=False, # import all exported symbols to caller's globals
    create_msg:bool=False # Add a message that lists usable tools
):
    "Import gist directly from string without saving to disk"
    fil = GhApi(sync=True).gist_file(gist_id)
    mod_name = mod_name or Path(fil['filename']).stem
    module = import_string(fil['content'], mod_name)
    glbs = currentframe().f_back.f_globals
    if add_global: glbs[mod_name] = module
    syms = getattr(module, '__all__', None)
    if syms is None: syms = [o for o in dir(module) if not o.startswith('_')]
    syms = [getattr(module, nm) for nm in syms]
    if import_wildcard:
        for sym in syms: glbs[sym.__name__] = sym
    if create_msg:
        pref = getattr(module, '__doc__', "Tools added to dialog:")
        asyncio.ensure_future(add_msg(f"{pref}\n\n{mk_toollist(syms)}"))
    return module

# %% ../nbs/06_utils.ipynb #aab4330e
def InputBtn(txt, value=None, btncls=(), **kw):
    btncls = ' '.join(f'uk-btn-{o}' for o in listify(btncls))
    return Button(txt, type='submit', name='user_input', value=value or txt, cls=f'uk-btn {btncls}', **kw)

def input(prompt='', *args):
    "Solveit customised input to handle fasttag prompts"
    return builtins.input(prompt if isinstance(prompt,str) else Solveit_input(prompt, *args))

def InputForm(*c, **kwargs):
    "Create an `input()` with a `Form` with needed `hx_post` and `id`"
    return input(Form(*c,
        hx_post="/input_reply_", id='input-request-form', **kwargs))
