"""Adds interactive widgets to solveit

Docs: https://AnswerDotAI.github.io/dialoghelperwidgets.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_widgets.ipynb.

# %% auto #0
__all__ = ['isl', 'fsl', 'irs', 'frs', 'Widget', 'oob_view', 'current_msg_id', 'run_msg_quiet', 'MonsterRangeBase', 'IntSlider',
           'FloatSlider', 'IntRangeSlider', 'FloatRangeSlider', 'ExcalidrawWidget']

# %% ../nbs/06_widgets.ipynb #5e8bbec6
from fastcore.utils import *
from fastcore.parallel import bg_task
from pyskills import allow
from fasthtml.common import *
from monsterui.all import Range
from .core import pop_data_a, add_html, call_endp, dh_settings
import uuid,io,base64,httpx,os,json
from PIL import Image

# %% ../nbs/06_widgets.ipynb #fdeaa604
class Widget:
    "Kernel-resident interactive widget; subclasses define `render` and `handle`"
    def __init__(self, state=None): self.id,self.state,self.task,self.oob_views,self.rerun_ids,self.oob_busy,self.oob_pending,self.rerun_busy,self.rerun_pending = 'w_'+uuid.uuid4().hex[:8],state,None,{},set(),False,False,False,False

# %% ../nbs/06_widgets.ipynb #036375b9
@patch
def bind(self:Widget, data_key='val', dom_prop='value', ms=50, **kw):
    fixed = ''.join(f"{k}:{v!r}," for k,v in kw.items())
    push = f"pushData('{self.id}', {{{fixed}{data_key}:v}})"
    return (f"var v=this.{dom_prop},e=this,n=Date.now();clearTimeout(e._tt);"
            f"if(n-(e._lt||0)>{ms}){{e._lt=n;{push};}}"
            f"else e._tt=setTimeout(function(){{e._lt=Date.now();{push};}},{ms});")

# %% ../nbs/06_widgets.ipynb #47103b2b
@patch
def render(self:Widget): raise NotImplementedError
@patch
def handle(self:Widget, data): raise NotImplementedError

# %% ../nbs/06_widgets.ipynb #1a00e826
@patch
async def refresh_oob_views(self:Widget):
    if self.oob_busy:
        self.oob_pending=True
        return
    self.oob_busy,self.oob_pending = True,False
    try:
        for vid,draw in self.oob_views.items(): add_html(Div(draw(), id=vid, hx_swap_oob='true'))
    finally: self.oob_busy = False
    if self.oob_pending: await self.refresh_oob_views()

# %% ../nbs/06_widgets.ipynb #a319e206
def oob_view(draw, *ws):
    "Shared out-of-band view repainted by any of `ws`"
    vid = 'v_'+uuid.uuid4().hex[:8]
    for w in ws: w.oob_views = {k:v for k,v in w.oob_views.items() if v is not draw}; w.oob_views[vid] = draw
    return Div(draw(), id=vid)


# %% ../nbs/06_widgets.ipynb #4df83226
def current_msg_id(): return call_endp('read_msg_', json=True, n=0)['id']

# %% ../nbs/06_widgets.ipynb #1efa5c1c
@patch
def live(self:Widget):
    self.rerun_ids.add(current_msg_id())
    return self.state

# %% ../nbs/06_widgets.ipynb #7a879dce
async def run_msg_quiet(ids, dname=None, timeout=5):
    dname = dname or __dialog_name
    data = dict(ids=ids, dlg_name=dname.strip('/'))
    async with httpx.AsyncClient() as c:
        await c.post(f'http://localhost:{dh_settings["port"]}/add_runq_', data=data, headers={'Accept':'application/json'}, timeout=timeout)

# %% ../nbs/06_widgets.ipynb #fe02181c
@patch
async def rerun_msgs(self:Widget):
    if self.rerun_busy: self.rerun_pending=True; return
    self.rerun_busy,self.rerun_pending = True,False
    try:
        for msg_id in self.rerun_ids: await run_msg_quiet(msg_id)
    finally: self.rerun_busy = False
    if self.rerun_pending: await self.rerun_msgs()

# %% ../nbs/06_widgets.ipynb #0feb5045
@patch
async def _listen(self:Widget):
    while True:
        d = await pop_data_a(self.id)
        if d.get('js_status')=='timeout': continue
        try:
            self.handle(d)
            bg_task(self.refresh_oob_views())
            bg_task(self.rerun_msgs())
        except Exception as e: print('handle err', e)

# %% ../nbs/06_widgets.ipynb #46e661db
@patch
def _ft(self:Widget):
    if not self.task: self.task = bg_task(self._listen())
    ft = self.render()
    ft.attrs['onclick'] = 'event.stopPropagation()'
    return ft
@patch
def __ft__(self:Widget): return self._ft()
@patch
def _repr_html_(self:Widget): return to_xml(self._ft())

# %% ../nbs/06_widgets.ipynb #058494c0
@patch
async def update(self:Widget, **d):
    self.handle(d)
    ft = self.render()
    ft.attrs['hx_swap_oob'] = 'true'
    add_html(ft)
    await self.refresh_oob_views()
    await self.rerun_msgs()

# %% ../nbs/06_widgets.ipynb #1f6d7fdf
allow({Widget:...})

# %% ../nbs/06_widgets.ipynb #9d4c3039
class MonsterRangeBase(Widget):
    def __init__(self, val, min=0, max=100, step=1):
        self.min,self.max,self.step = min,max,step
        super().__init__(val)
    def _val_str(self): return str(self.state)
    def _parse(self, s): return float(s)
    def render(self):
        js = f"document.getElementById('{self.id}').addEventListener('uk-input-range:input',function(){{{self.bind()}}});"
        return Div(Range(value=self._val_str(), min=self.min, max=self.max, step=self.step, label=True, id=self.id),
                   Script(js), id=self.id+'_wrap', style='max-width:16rem;padding-top:0.5rem;padding-left:0.5rem')
    def handle(self, data): self.state = self._parse(data['val'])

# %% ../nbs/06_widgets.ipynb #801b22ec
class IntSlider(MonsterRangeBase):
    def __init__(self, val=0, min=0, max=100, step=1): super().__init__(val, min, max, step)
    def _parse(self, s): return int(float(s))

# %% ../nbs/06_widgets.ipynb #27d0d080
isl = IntSlider()
isl

# %% ../nbs/06_widgets.ipynb #382633fe
class FloatSlider(MonsterRangeBase):
    def __init__(self, val=0., min=0., max=100., step=0.1): super().__init__(val, min, max, step)

# %% ../nbs/06_widgets.ipynb #7d243f91
fsl = FloatSlider()
fsl

# %% ../nbs/06_widgets.ipynb #745030f9
class IntRangeSlider(MonsterRangeBase):
    def __init__(self, val=(0,100), min=0, max=100, step=1): super().__init__(list(val), min, max, step)
    def _val_str(self): return f'{self.state[0]},{self.state[1]}'
    def _parse(self, s): return [int(float(x)) for x in str(s).split(',')]

# %% ../nbs/06_widgets.ipynb #4e8832a2
irs = IntRangeSlider()
irs

# %% ../nbs/06_widgets.ipynb #fa6a2906
class FloatRangeSlider(MonsterRangeBase):
    def __init__(self, val=(0.,100.), min=0., max=100., step=0.1): super().__init__(list(val), min, max, step)
    def _val_str(self): return f'{self.state[0]},{self.state[1]}'
    def _parse(self, s): return [float(x) for x in str(s).split(',')]

# %% ../nbs/06_widgets.ipynb #e231c54f
frs = FloatRangeSlider()
frs

# %% ../nbs/06_widgets.ipynb #a9cb67c1
class ExcalidrawWidget(Widget):
    def __init__(self, scene=None, h=650): self.h = h; super().__init__(scene or dict(elements=[], appState={}, files={}))
    def _plain(self, o):
        if isinstance(o, dict): return {k:self._plain(v) for k,v in o.items()}
        if isinstance(o, (list,tuple,L)): return [self._plain(v) for v in o]
        return o
    def handle(self, d):
        scene = self._plain(d.get('scene', {}))
        self.state = dict(elements=scene.get('elements', []), appState=scene.get('appState', {}), files=scene.get('files', {}), image_base64=d.get('image_base64', self.state.get('image_base64', '')))
    
    def render(self):
        scene,host = json.dumps(dict(elements=self._plain(self.state.get('elements', [])), appState=self._plain(self.state.get('appState', {})), files=self._plain(self.state.get('files', {})))),f'{self.id}_host'
        inbox = f'{self.id}_inbox'
        css = '.excalidraw .default-sidebar-trigger,.excalidraw [data-testid="main-menu-trigger"],.excalidraw .main-menu-trigger,.excalidraw [data-testid="toolbar-more-tools"],.excalidraw .App-toolbar__extra-tools-trigger{display:none!important;}'
        tips = 'AI tips: use self.get_pil() to inspect the canvas; use self.state to inspect raw scene coordinates; use self.add(...) to add elements.'
        js = f"""\
import * as ExcalidrawLib from "https://esm.sh/@excalidraw/excalidraw@0.18.0?deps=react@18.2.0,react-dom@18.2.0";
import React from "https://esm.sh/react@18.2.0";
import ReactDOM from "https://esm.sh/react-dom@18.2.0/client";
window.EXCALIDRAW_ASSET_PATH = "https://esm.sh/@excalidraw/excalidraw@0.18.0/dist/prod/";
window._xw = window._xw||{{}};
let el = document.getElementById("{host}");
if (!el.dataset.mounted) {{
  let root = ReactDOM.createRoot(el), to_data = b => new Promise(r => {{ let fr = new FileReader(); fr.onloadend = () => r(fr.result); fr.readAsDataURL(b); }});
  let onChange = async (elements, appState, files) => {{
    let scene = {{elements, appState, files}}, image_base64 = "";
    if (elements.length) try {{ image_base64 = await to_data(await ExcalidrawLib.exportToBlob({{elements, appState, files, mimeType:"image/png"}})); }} catch {{}}
    pushData("{self.id}", {{scene, image_base64}});
  }};
  root.render(React.createElement("div", {{style:{{height:"{self.h}px"}}}}, React.createElement(ExcalidrawLib.Excalidraw, {{initialData:{scene}, onChange, excalidrawAPI:api => window._xw["{self.id}"] = api}})));
  let ib = document.getElementById("{inbox}");
  new MutationObserver(() => {{
    let t = ib.textContent.trim(); if (!t) return; ib.textContent = "";
    let api = window._xw["{self.id}"]; if (!api) return;
    let add = ExcalidrawLib.convertToExcalidrawElements(JSON.parse(t));
    api.updateScene({{elements:[...api.getSceneElements(), ...add]}});
    if (api.scrollToContent) api.scrollToContent(add);
  }}).observe(ib, {{childList:true, characterData:true, subtree:true}});
  el.dataset.mounted = 1;
}}
"""
        return Div(Style(css), Link(rel='stylesheet', href='https://esm.sh/@excalidraw/excalidraw@0.18.0/dist/dev/index.css'), Pre(tips, style='display:none'), Div(id=host), Div(id=inbox, style='display:none'), Script(js, type='module'), id=self.id)
    
    def add(self, *els):
      "Expects dicts as defined in: https://raw.githubusercontent.com/excalidraw/excalidraw/refs/heads/master/dev-docs/docs/%40excalidraw/excalidraw/api/excalidraw-element-skeleton.mdx"
      add_html(Div(json.dumps(list(els)), id=self.id+'_inbox', hx_swap_oob='innerHTML'))

    def get_pil(self):
        img = self.state.get('image_base64', '')
        if not img: return None
        return Image.open(io.BytesIO(base64.b64decode(img.split(',', 1)[-1])))
